# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - prompt-vault

on:
  push:
    branches:
      - master
    paths: ["backend/**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "microsoft"

      - name: Generate secrets.properties
        run: |
          cd Backend/src/main/resources
          pwd
          echo "ISSUER=${{ secrets.ISSUER }}" > secrets.properties
          echo "AUDIENCE=${{ secrets.AUDIENCE }}" >> secrets.properties
          echo "DB_CONNECT=${{ secrets.DB_CONNECT }}" >> secrets.properties

      - name: Build with Maven
        run: |
          cd backend
          mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: "${{ github.workspace }}/target/*.jar"

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A33093C80C914473954895AC41AC63E0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_467B5B73FE594462BA470A76D65C5148 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_06E406EC749940E1A61631F6360724F0 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "prompt-vault"
          slot-name: "Production"
          package: "*.jar"
